# Generated by Django 5.2.4 on 2025-07-31 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_de_peliculas_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pelicula',
            old_name='anio',
            new_name='fecha_estreno',
        ),
    ]
