# Generated by Django 5.2.4 on 2025-08-15 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_de_peliculas_app', '0002_rename_anio_pelicula_fecha_estreno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('director', models.CharField(max_length=100)),
                ('genero', models.CharField(max_length=50)),
                ('fecha_estreno', models.IntegerField()),
            ],
        ),
    ]
